services:
  master:
    image: locustio/locust
    ports:
      - "8089:8089"
    volumes:
      - ./:/mnt/locust
    command: -f /mnt/locust/locustfile-issue-async.py --master -H http://host.docker.internal:8080
    extra_hosts:
      - "host.docker.internal:${HOST_IP}"

  worker:
    image: locustio/locust
    scale: 3
    volumes:
      - ./:/mnt/locust
    command: -f /mnt/locust/locustfile-issue-async.py --worker --master-host master
    extra_hosts:
      - "host.docker.internal:${HOST_IP}"
