-- schema.sql 스크립트를 실행해서 어플리케이션 로딩시점에 데이터베이스 초기화
drop table if exists item CASCADE;
create table item
(
    id        bigint generated by default as identity,
    item_name varchar(10),
    price     integer,
    quantity  integer,
    primary key (id)
);

