spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/jpashop  # server mode
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create  # drop and recreate table in execution time
    properties:
      hibernate:
#        show_sql: true  # print out
        format_sql: true

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace