logging:
  level:
    org.apache.coyote.http11: trace # ????? http ?? ?? ??

file:
  dir: /Users/jeongwpa/projects/file/

spring:
  servlet:
    multipart:
      max-file-size: 1MB      # ?? ??? ?? ???
      max-request-size: 10MB  # ?? ??? ?? ?? ?? ???
      enabled: true           # ?? ??? ???, ???? true
