spring:
  application:
    name: splearn
  datasource:
    url: jdbc:mysql://localhost:3306/splearn?useSSL=false&allowPublicKeyRetrieval=true
    username: spring
    password: secret
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
